services:
    ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml
        ports:
          - 4040:4040
    flask:
        build:
          context: .
        # flask requires SIGINT to stop gracefully
        # (default stop signal from Compose is SIGTERM)
        stop_signal: SIGINT
        ports:
          - 5000:5000